compile: 
	gcc cross-ref.c -o cross-ref 
	./cross-ref irving-little-573.txt 
clean: 
	rm cross-ref
	rm -rf cross-ref
london:
	gcc cross-ref.c -o cross-ref 
	./cross-ref irving-london-598.txt 
little:
	gcc cross-ref.c -o cross-ref 
	./cross-ref irving-little-573.txt 